export const ActionType = {
  SIDEBAR: "SIDEBAR",
  CUSTOMERID: "CUSTOMERID",
  FLAVOURCATEGORY: "FLAVOURCATEGORY",
  MASPRODUCTLINE: "MASPRODUCTLINE",
  NONPURCHASE: "NONPURCHASE",
  SERVICE: "SERVICE",
  PRODUCTID: "PRODUCTID",
  TECHNOLOGY: "TECHNOLOGY",
};
